macos/patches: Backport QT macOS docking fixes
obsproject/obs-deps pull request #102
Opened 2022-04-10 11:50 UTC by gxalpha

### Description

Backports qt/qtbase@78b6050 and qt/qtbase@3224c6d, fixing the broken macOS
docking and undocking.

These fixes are documented to fix [QTBUG-70137](https://bugreports.qt.io/browse/QTBUG-70137), where docks will freak out when getting dragged out of the UI; however they also happens to fix [QTBUG-64483](https://bugreports.qt.io/browse/QTBUG-64483) (floating docks randomly deciding they lost there will to live, and no longer being re-dockable) (@RytoEX has been watching that one).

These two bugs were the biggest troublemakers in terms of docking and undocking on macOS.
The patches are no longer needed once we move to QT 6.2 (which is were they are from), but for now I think they are really important (and perhaps could even justify a macOS hotfix on their own).

### Motivation and Context

Docking can get very broken on macOS.
This makes it better. Not perfect, but much better..

### How Has This Been Tested?

Built on GHA and compiled my OBS against it.
Test QT artifacts [here](https://github.com/gxalpha/obs-deps/actions/runs/2143386691), so that you don't need to wait two hours for QT to compile.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-04-18 15:25 UTC, RytoEX commented
Do we not need the third patch that amends the second patch? See:
* https://github.com/qt/qtbase/commit/ba3e1fe09b7d921985e21d857a1d566465095e69
* https://codereview.qt-project.org/c/qt/qtbase/+/362850

2022-04-18 15:26 UTC, RytoEX requested changes
Commit message nit: QT -> Qt

2022-04-18 16:45 UTC, gxalpha commented
Fixed the commit message, I'll leave the decision on https://github.com/qt/qtbase/commit/ba3e1fe09b7d921985e21d857a1d566465095e69 to you, see my comment above.

2022-04-18 16:56 UTC, RytoEX commented
We can leave the third patch out if it's truly not needed. We can always land this now and add it later if we find a need. I'm honestly not entirely sure what cases/issues it fixes.

On the other hand, it might be less annoying to just add it now so we don't have to re-release later should we find it useful.

Thoughts @PatTheMav ?

2022-04-18 17:53 UTC, PatTheMav commented
There is the potential of the omitted patch fixing other behaviour that later patches somehow rely on, but until that is confirmed I'm fine with it.

2022-04-20 19:27 UTC, RytoEX commented
> We don't set a custom title bar widget anywhere

We don't currently, but see https://github.com/obsproject/obs-studio/pull/6358. I don't know if that will be merged, but I'm tempted to err on the side of caution and just include the third patch if that PR would be affected. I'm leaning towards just including the extra patch since it was tagged on the QTBUG, and I don't want to have to remember that we didn't include it if this somehow later comes up.

Otherwise, this seems fine to me, so it will likely be merged one way or another.

2022-04-20 19:55 UTC, gxalpha commented
I also saw that PR, and with that in mind I also lean towards including the patch - I'll add it to this PR tomorrow or so

2022-04-21 20:35 UTC, gxalpha commented
Added the third patch.
Didn't test it locally since building Qt takes ages on my machine, but as long the patch applies cleanly on CI this should be good (can't see the patch doing any harm).

2022-04-21 21:59 UTC, RytoEX commented
> Added the third patch. Didn't test it locally since building Qt takes ages on my machine, but as long the patch applies cleanly on CI this should be good (can't see the patch doing any harm tbh).
> 
> Edit: CI restored from cache. Are you kidding me? :D

Yeah, the cache key is `'qt-cache-${{ matrix.arch }}-${{ env.QT_REVISION }}'`, so any build within 7 days that doesn't change the key would use the cache and then skip building. It's kind of a shame it won't restore the cache and then check for new patches. We could probably do it, but it would require reworking the skip step logic.

2022-05-07 01:02 UTC, RytoEX approved these changes

2022-05-07 01:02 UTC, merged