Properly support multiple VS versions on Windows
obsproject/obs-deps pull request #108
Opened 2022-05-30 12:50 UTC by WizardCM

### Description

After failing to build obs-deps on Windows, coordinated with @PatTheMav to find a solution that'd fix building.

If multple copies of VIsual Studio are detected, sort the list and choose the oldest version installed.

### Motivation and Context

If more than one copy of Visual Studio is installed, `MSFT_VSInstance` will return an array of objects, causing the rest of the build script to fail.

Additionally, detours failed to build as it bypassed the Find-VisualStudio function, resulting it bypassing the included fix.

### How Has This Been Tested?

* Attempt to build obs-deps on a machine where more than one version/copy of Visual Studio is installed.
* Tested with 2019 and 2022 installed. With these changes, 2019 is selected.

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-05-30 12:52 UTC, WizardCM commented
Pat has mentioned he's unsure whether this should prioritise the older or the newer Visual Studio. In an ideal world, developers should remove outdated/unused/legacy Visual Studio installations.

I think for a simple fix like this PR, we should prioritise newer versions.

Ideally the proper fix should be a little more complex. We should have a "recommended" version that we try and spot first (such as 16.x) and fall back to other versions.

2022-05-30 12:59 UTC, PatTheMav commented on utils.pwsh/Invoke-DevShell.ps1
>          . $PSScriptRoot/Utils-Logger.ps1
While we're here, you might want to change this to import "Logger.ps1" - that line contains the old filename. It just doesn't break as long as you don't import "Invoke-DevShell.ps1" standalone.

2022-05-30 13:00 UTC, PatTheMav commented on utils.pwsh/Setup-Target.ps1
> +    $VisualStudioId = "Visual Studio {0} {1}" -f @(
You don't need those lines - just the 3 lines above flattening a possible array to a single object.

2022-05-30 13:00 UTC, PatTheMav requested changes
See inline comments.

2022-05-30 17:17 UTC, jpark37 commented
> If multple copies of VIsual Studio are detected, sort the list and choose the oldest version installed.

Sometimes having older VS installed is unavoidable, e.g. need plugins that aren't available on newer VS. I would prioritize a fixed version, then new to old.

2022-06-08 14:09 UTC, RytoEX requested changes
> Sometimes having older VS installed is unavoidable, e.g. need plugins that aren't available on newer VS. I would prioritize a fixed version, then new to old.

I agree with this earlier feedback. As we currently design for VS2019, we should prefer that in the selection, then cycle through installed versions, new to old. That said, I expect to transition obs-deps and obs-studio to VS2022 by the end of June.

Are the objects returned actually guaranteed to be in a specific order? Or are we assuming that they are?

2022-07-06 18:00 UTC, RytoEX approved these changes
I've force pushed changes to ensure that only VS2019+ versions are selected into the object. This ensures that we don't end up in a scenario where a user has VS2017 and VS2019 installed and the sorted object array ends up with VS2017 in slot 0, which results in the next check (`-or ( $VisualStudioData.Version -lt 16`) failing in a confusing manner.

2022-07-06 18:00 UTC, PatTheMav approved these changes

2022-07-06 18:11 UTC, merged