[WIP] Add libdatachannel
obsproject/obs-deps pull request #163
Opened 2023-03-14 02:07 UTC by DDRBoxman

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2023-03-17 13:42 UTC, tytan652 commented on deps.macos/90-libdatachannel.zsh
> +    -DPYTHON_LIBRARY=$(brew --prefix)/opt/python3/lib/
You are building Mbeb TLS submodule inside of libdatachannel and not using the "system" one.

```suggestion
    -DUSE_SYSTEM_MBEDTLS=ON
```

2023-03-17 13:43 UTC, tytan652 requested changes
Please ignore this one.

2023-03-17 13:43 UTC, tytan652 commented on requirements.txt
Not needed if we skip Mbed TLS submodule.

2023-03-17 13:43 UTC, tytan652 commented on utils.zsh/20-host.zsh
> +    python3 -m pip install -r "${project_root}"/requirements.txt
Not needed if we skip Mbed TLS submodule.

2023-03-21 06:04 UTC, tytan652 requested changes
`USE_SYSTEM_MBEDTLS` no longer exist since the submodule got dropped recently.

2023-03-21 06:04 UTC, tytan652 commented on deps.macos/90-libdatachannel.zsh
> +    -DUSE_SYSTEM_MBEDTLS=1
```suggestion
```

2023-03-21 06:04 UTC, tytan652 commented on deps.windows/70-libdatachannel.ps1
> +        '-DUSE_SYSTEM_MBEDTLS=1'
```suggestion
```

2023-03-23 20:36 UTC, RytoEX commented
> We still need a solution to deal with the fact that on windows we now have a mbedtls from mingw and a mbedtls compiled with msvc.

We used to do this before the obs-deps rewrite. Check back in the git history between November 2021 and May 2022. I think we just copied the native build over top of the MinGW build, because the MinGW build was only used for libsrt or something like that.

2023-03-25 17:26 UTC, closed without merging