deps.macos: Add syphon framework
obsproject/obs-deps pull request #176
Opened 2023-04-01 08:33 UTC by gxalpha

### Description
Adds syphon to obs-deps.
The workflow pulls their git repository (https://github.com/Syphon/Syphon-Framework) at the specified git commit (they don't seem to tag releases anymore).
Building builds the `Syphon` target of their distributed Xcode project, which generates a `Syphon.framework`.
Along with the debug symbols, this then gets copied to the `lib` directory.

### Motivation and Context
The OBS syphon plugin is currently using a 9(!) year old version of the syphon framework on a OBS contributors' fork because it had to be patched for IOSurfaces to be accessible (fun fact: Not counting the custom patches, it's exactly 9 years old to the day, see the [commit history](https://github.com/palana/Syphon-Framework/commits/master)).
Seeing that obs-deps wasn't a thing back then, it currently is a git submodule. This also means isn't built by Syphon's build system, with the source files instead just being stringed together by our obs-studio cmake.

Building syphon on obs-deps fixes these issues. It means that we can more easily update syphon (this PR of course brings in the latest version already), and utilizes their Xcode project to compile. It also reduces OBS' build time since the dependency doesn't need to be built with OBS.

### How Has This Been Tested?
Tested on my fork to correctly generate the `Syphon.framework` framework: https://github.com/gxalpha/obs-deps/actions/runs/4574746519
Built and ran their [sample server](https://github.com/Syphon/Simple) against this framework successfully (a non-recursive clone will avoid bringing in the submodule).
Had an OBS with the required cmake- and code-changes build and run against it. Successfully captured the sample servers' output.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-04-01 14:29 UTC, PatTheMav approved these changes

2023-04-02 02:11 UTC, RytoEX requested changes
Commit message nit: use "Syphon Framework".

2023-04-02 05:02 UTC, gxalpha commented
Fixed

2023-05-30 17:07 UTC, RytoEX approved these changes
Looks good to me.

2023-05-30 18:51 UTC, merged