deps.ffmpeg: Update srt to 1.5.2rc2
obsproject/obs-deps pull request #191
Opened 2023-06-05 18:02 UTC by pkviet

### Description
This updates srt to 1.5.2 rc2. This has a commit which fixes a bug with rendezvous mode.
This is a draft and will be updated to 1.5.2 which should be released in a few weeks (private conversation with libsrt devs).

### Motivation and Context
Fix bug and keep up-to-date deps.

### How Has This Been Tested?
Builds fine locally on wsl.

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 
- Tweak (non-breaking change to improve existing functionality) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-06-30 14:45 UTC, RytoEX requested changes

2023-06-30 14:45 UTC, RytoEX commented on deps.ffmpeg/60-srt.zsh
> +local hash="${0:a:h}/checksums/v1.5.2-rc.2.tar.gz.sha256"
Checksum filename needs to match.

2023-06-30 16:10 UTC, pkviet commented on deps.ffmpeg/60-srt.zsh
> +local hash="${0:a:h}/checksums/v1.5.2-rc.2.tar.gz.sha256"
fixed

2023-06-30 16:11 UTC, pkviet commented
i've fixed the mishap and retested srt to YouTube and local srt-live-transmit; worked fine.

2023-07-06 19:09 UTC, RytoEX requested changes
Commit message and PR title nit:
* use "libsrt" instead of "srt", in line with commit history

2023-07-07 05:02 UTC, pkviet commented
> Commit message and PR title nit:
> 
> * use "libsrt" instead of "srt", in line with commit history

fixed.
Tested that caller / listener / rendezvous mode are all working.

2023-07-12 17:26 UTC, RytoEX approved these changes
Seems fine. If you've done testing, this should be fine.

2023-07-12 20:56 UTC, merged