Windows x86 deprecation
obsproject/obs-deps pull request #196
Opened 2023-06-30 19:48 UTC by PatTheMav

### Description
Removes x86 slices of most Windows dependencies, with the exception of Detours and Vulkan, which are both needed for capture plugins.

### Motivation and Context
Deprecate all traces of standalone x86 OBS Studio versions.

### How Has This Been Tested?
Tested on Windows 11 VM.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-06-30 21:04 UTC, RytoEX requested changes
Do the first two commits individually work in the absence of the third commit? It looks like they should, but I wanted to confirm.

Commit message nit:
* detours -> Detours

2023-06-30 21:55 UTC, PatTheMav commented
> Do the first two commits individually work in the absence of the third commit? It looks like they should, but I wanted to confirm.
> 
> Commit message nit:
> 
> * detours -> Detours

They should, yeah.

2023-07-07 18:00 UTC, RytoEX approved these changes
Seems fine. The one thing to watch out for is that it will become impossible to do full 32-bit builds in legacy CMake, so it may be helpful (though perhaps not required) to have instructions for a slim 32-bit build with just the win-capture and win-dshow components.

2023-07-17 15:29 UTC, RytoEX commented
Per off-thread discussion, we're going to hold off on merging this change because removing the x86 Windows deps would make doing complete Windows legacy CMake builds of obs-studio a bit burdensome. We'll remove the x86 Windows deps once we remove the legacy CMake.

2024-08-22 20:57 UTC, RytoEX commented
Can this be merged before #190?

2024-08-22 21:35 UTC, RytoEX commented
Let's cut down CI's workload then.

2024-08-22 21:35 UTC, merged