deps.qt: Add Qt Designer
obsproject/obs-deps pull request #243
Opened 2024-04-08 21:29 UTC by derrod

### Description

Build Qt Designer with our Qt deps 

### Motivation and Context

We should have always have a readily available version of designer people can use without having to suffer through Qt's maintenance tool.

### How Has This Been Tested?

We'll see if we compile ey?

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-04-09 07:47 UTC, derrod commented
For some reason designer components were built, but the binary `designer.exe` was not created/installed, I guess this will require another dive into Qt Cmake...

2024-05-04 00:44 UTC, RytoEX commented
I did some digging and it looks like `-DQT_BUILD_TOOLS_BY_DEFAULT:BOOL=OFF` is the culprit here. We can try setting it back to ON just in the qttools configuration.

I filed [QTBUG-125067](https://bugreports.qt.io/browse/QTBUG-125067) in case this behavior is not intentional.

2024-05-04 05:06 UTC, derrod commented
Yeah setting that to `ON` just for `qttools` works, latest CI artifact has Qt Designer binaries.

2024-05-05 02:47 UTC, RytoEX requested changes
Nit on configure option order. Besides that, and the additional time required to build this, the PR contents are fine.

2024-05-05 02:47 UTC, RytoEX commented on deps.qt/qt6.zsh
> +          -DFEATURE_qtattributionsscanner:BOOL=OFF
```suggestion
          -DFEATURE_qtattributionsscanner:BOOL=OFF
          -DFEATURE_qtdiag:BOOL=OFF
          -DFEATURE_qtplugininfo:BOOL=OFF
```

2024-05-06 17:40 UTC, RytoEX approved these changes
The contents of the PR are fine. The additional build time is unfortunate, but I don't know how else we're going to have a version of Designer that matches our Qt version.

2024-05-07 21:36 UTC, merged