Add universal build support for macOS
obsproject/obs-deps pull request #58
Opened 2021-06-07 18:06 UTC by Developer-Ecosystem-Engineering

### Description
- Update all dependencies to universal
- Enable NEON for several projects
- Support building on macOS 10.15 or macOS 11, x86, Rosetta or natively

### Motivation and Context
- OBS does not currently build universal but the dependencies would support it

### How Has This Been Tested?
Tested on macOS 11.3 M1 & Rosetta
Tested on macOS 10.15.7 x86
Xcode 12.4

### Types of changes
- New feature (non-breaking change which adds functionality - Apple silicon support)
- Performance enhancement (non-breaking change which improves efficiency - NEON support in some libraries)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-06-07 19:03 UTC, RytoEX requested changes
You don't need to modify `build-script-macos-01.sh` or `build-script-macos-02.sh`.  Those files are generated from `.github/workflows/create_scripts.yml` after each commit to the master branch.

2021-06-07 19:37 UTC, Developer-Ecosystem-Engineering commented on .github/workflows/build_deps.yml
> +      LIBX264_VERSION: '2021-05-05'
Okay thanks done!

2021-06-07 19:39 UTC, Developer-Ecosystem-Engineering commented
> You don't need to modify `build-script-macos-01.sh` or `build-script-macos-02.sh`. Those files are generated from `.github/workflows/create_scripts.yml` after each commit to the master branch.

Was mostly to demonstrate what it generates for observers that are interested in building on their own without needing to generate it themselves. I can remove them if desired, as you point out they are auto generated anyway from the .yml (which is how they were generated for this PR of course)

2021-06-07 20:08 UTC, PatTheMav commented
Yeah it's fine for the PR, especially as it will only be overwritten after merging iirc.

2021-06-08 04:00 UTC, Developer-Ecosystem-Engineering commented
Chasing environment failures in the build env, will see if we can setup a local environment to replicate before subsequent amendments.

2021-07-21 17:33 UTC, Developer-Ecosystem-Engineering commented
These changes have been integrated into https://github.com/obsproject/obs-deps/pull/60. Do we want to leave this open or just use that one?

2021-07-21 20:48 UTC, RytoEX commented
> 
> 
> These changes have been integrated into #60. Do we want to leave this open or just use that one?

My personal preference is that PRs are narrowly scoped and reviewed on their own merits, but I'll defer to @DDRBoxman and @PatTheMav on this since it's macOS heavy.

If this is to be merged, it will need the commits appropriately squashed and the build failure resolved or explained.

2021-08-17 02:23 UTC, DDRBoxman commented
Closing this since #60 is merged :)

2021-08-17 02:23 UTC, closed without merging